# 참고: appspec.yml 파일은 민감(?)하기 때문에 공백까지 정확하게 기입해주셔야 합니다.

version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/build/
# source는 로컬의 어떤 파일들을 EC2로 옮길지에 대한 것입니다. 현재는 모든 파일("/")을 선택하고 있습니다.
# destination은 로컬로부터 받아온 파일들을 EC2 instance 어디에 저장할 지에 대한 것입니다.
# 현재는 /home/ubuntu/build/ 라는 경로를 지정하고 있습니다.
# 아직 우리는 build라는 디렉토리를 EC2 instance 안에 생성하지 않았기 때문에, 이후에 생성할 것입니다.

hooks:
  BeforeInstall:
      - location: scripts/beforeInstall.bash
        runas: root
  AfterInstall:
      - location: scripts/afterInstall.bash
        runas: root
# 로컬의 파일을 받아오기 전에(BeforeInstall) 실행할 스크립트를 지정합니다.
# 로컬의 파일을 받아온 다음에(AfterInstall) 실행할 스크립트를 지정합니다.