var express = require("express");
var bodyParser = require("body-parser");
var cookieParser = require("cookie-parser");
var dotenv = require("dotenv");
var cors = require("cors");
var morgan = require("morgan");
var logger = require("../app/src/config/logger");
var app = express();
dotenv.config();
app.set("views", "./src/views");
app.set("view engine", "ejs");
app.use(express.static(__dirname + "/src/public"));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(cors());
app.use(morgan("tiny", { stream: logger.stream }));
var view = require("./src/apis/view");
var root = require("./src/apis/root");
var watchList = require("./src/apis/watch-list");
var image = require("./src/apis/image");
var search = require("./src/apis/search");
var boards = require("./src/apis/boards");
var purchase = require("./src/apis/purchase-list");
var sale = require("./src/apis/sale-list");
var notification = require("./src/apis/notification");
var profile = require("./src/apis/profile");
app.use("/", view);
app.use("/api/", root);
app.use("/api/watchlist", watchList);
app.use("/api/image", image);
app.use("/api/search", search);
app.use("/api/boards", boards);
app.use("/api/purchase-list", purchase);
app.use("/api/sale-list", sale);
app.use("/api/notification", notification);
app.use("/api/students", profile);
module.exports = app;
